pipeline {
    agent any
    environment{
        IMAGE_NAME = "asruiz1235/python-app"
        DOCKERHUB_CREDS = credentials('docker')
        RepoDockerHub = 'sebarray'
        NameContainer = 'curso'
    }

    stages {
        stage('Build image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} ./python-app'
            }
        }
    }
}